<?php
//CMS cache file, DO NOT modify me!
//Created on June 12, 2010, 10:31

$SYS_ENV = array (
  'backupPath' => '../backup',
  'hostname' => NULL,
  'sysname' => 'http://172.27.203.81:8080/subject/djnews/71/CMSware/',
  'version' => 'CMSware 2.5 Plus Stable',
  'templatePath' => '../templates',
  'smtp_host' => '',
  'smtp_username' => '',
  'smtp_password' => '',
  'smtp_from_email' => NULL,
  'smtp_auth' => '',
  'upImgType' => 'png|gif|jpeg|jpg',
  'upImgSize' => '10000',
  'upAttachType' => 'zip|rar|doc|xls|txt',
  'upAttachSize' => '1000',
  'tasktimeout' => '1276236718',
  'sitename' => NULL,
  'uploadPath' => NULL,
  'ResourceNum' => '530',
  'upload_flash_num' => '32',
  'upload_attach_num' => '44',
  'uploadUrl' => NULL,
  'upFlashSize' => '10000',
  'openTask' => '',
  'ResourcePath' => '../resource',
  'localImgIgnoreURL' => '{localhost}{127.0.0.1}{172.27.203.81:8080}',
  'publishResourceNum' => '11084',
  'is_safe_mode' => '',
  'ftp_server' => '',
  'ftp_server_port' => '',
  'ftp_user_name' => '',
  'ftp_user_pass' => '',
  'ftp_cms_admin_path' => '',
  'language' => '',
  'DisplayNodeID' => '1',
  'CollectionPageNum' => '15',
  'ContentPageNum' => '15',
  'SearchPageNum' => '15',
  'sessionTimeout' => '120',
  'isLogLogin' => '',
  'isLogAdmin' => '',
  'DisplayPublishCount' => '1',
  'LoginTryTime' => '15',
  'LoginTryCount' => '5',
  'enable_gzip' => '0',
  'AutoPageLen' => '2000',
  'EnableWaterMark' => '0',
  'WaterMarkImgPath' => '../html/WaterMark.gif',
  'WaterMarkPosition' => '1',
  'EnableCLWaterMark' => '0',
  'ContentViewMode' => '1',
  'CollectionViewMode' => '1',
  'ContributionViewMode' => '1',
  'DefaultResourcePSN' => '',
  'DefaultResourcePSNURL' => '',
  'DefaultContentPSN' => '',
  'DefaultContentPSNURL' => '',
  'DialogFitXP' => '1',
  'EnableEditorWaterMark' => '0',
  'AutoRefreshTree' => '0',
);
?>