<?php
//CMS cache file, DO NOT modify me!
//Created on June 10, 2010, 14:44

$CONTENT_MODEL_INFO = array (
  1 => 
  array (
    'TableID' => '1',
    'Name' => '新闻系统模型',
    'DSNID' => '1',
    'TitleField' => 'Title',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '1',
        'TableID' => '1',
        'FieldTitle' => '标题',
        'FieldName' => 'Title',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => 'notnull',
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻的标题',
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '10',
        'TableID' => '1',
        'FieldTitle' => '标题颜色',
        'FieldName' => 'TitleColor',
        'FieldType' => 'varchar',
        'FieldSize' => '7',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'color',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '1',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '2',
        'TableID' => '1',
        'FieldTitle' => '作者',
        'FieldName' => 'Author',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻的原作者',
        'FieldOrder' => '2',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '26',
        'TableID' => '1',
        'FieldTitle' => '外部链接',
        'FieldName' => 'OtherLink',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '3',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '4',
        'TableID' => '1',
        'FieldTitle' => '新闻图片',
        'FieldName' => 'Photo',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '4',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '6',
        'TableID' => '1',
        'FieldTitle' => '新闻内容',
        'FieldName' => 'Content',
        'FieldType' => 'longtext',
        'FieldSize' => NULL,
        'FieldInput' => 'RichEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '5',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '7',
        'TableID' => '1',
        'FieldTitle' => '关键字',
        'FieldName' => 'Keywords',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '6',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '5',
        'TableID' => '1',
        'FieldTitle' => '副标题',
        'FieldName' => 'SubTitle',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '7',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      8 => 
      array (
        'ContentFieldID' => '8',
        'TableID' => '1',
        'FieldTitle' => '来源网站',
        'FieldName' => 'FromSite',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '8',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      9 => 
      array (
        'ContentFieldID' => '3',
        'TableID' => '1',
        'FieldTitle' => '责任编辑',
        'FieldName' => 'Editor',
        'FieldType' => 'varchar',
        'FieldSize' => '20',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => '新闻编辑',
        'FieldOrder' => '9',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      10 => 
      array (
        'ContentFieldID' => '21',
        'TableID' => '1',
        'FieldTitle' => '自定义相关文章 ',
        'FieldName' => 'CustomLinks',
        'FieldType' => 'contentlink',
        'FieldSize' => NULL,
        'FieldInput' => 'select',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '10',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '0',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
      11 => 
      array (
        'ContentFieldID' => '9',
        'TableID' => '1',
        'FieldTitle' => '简介',
        'FieldName' => 'Intro',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '11',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '0',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'Content',
  ),
  2 => 
  array (
    'TableID' => '2',
    'Name' => '下载系统模型',
    'DSNID' => '1',
    'TitleField' => 'SoftName',
    'Model' => 
    array (
      0 => 
      array (
        'ContentFieldID' => '18',
        'TableID' => '2',
        'FieldTitle' => '软件名称',
        'FieldName' => 'SoftName',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '0',
        'FieldListDisplay' => '1',
        'IsMainField' => '0',
        'IsTitleField' => '1',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      1 => 
      array (
        'ContentFieldID' => '22',
        'TableID' => '2',
        'FieldTitle' => '界面预览',
        'FieldName' => 'Photo',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '1',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      2 => 
      array (
        'ContentFieldID' => '23',
        'TableID' => '2',
        'FieldTitle' => '本地上传',
        'FieldName' => 'LocalUpload',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => 'upload_attach',
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '2',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      3 => 
      array (
        'ContentFieldID' => '15',
        'TableID' => '2',
        'FieldTitle' => '软件类别',
        'FieldName' => 'SoftType',
        'FieldType' => 'varchar',
        'FieldSize' => '50',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '3',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      4 => 
      array (
        'ContentFieldID' => '17',
        'TableID' => '2',
        'FieldTitle' => '软件大小',
        'FieldName' => 'SoftSize',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '4',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      5 => 
      array (
        'ContentFieldID' => '16',
        'TableID' => '2',
        'FieldTitle' => '软件语言',
        'FieldName' => 'Language',
        'FieldType' => 'varchar',
        'FieldSize' => '10',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '5',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      6 => 
      array (
        'ContentFieldID' => '14',
        'TableID' => '2',
        'FieldTitle' => '运行环境',
        'FieldName' => 'Environment',
        'FieldType' => 'varchar',
        'FieldSize' => '50',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '6',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      7 => 
      array (
        'ContentFieldID' => '13',
        'TableID' => '2',
        'FieldTitle' => '软件评级',
        'FieldName' => 'Star',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '7',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      8 => 
      array (
        'ContentFieldID' => '20',
        'TableID' => '2',
        'FieldTitle' => '软件关键字',
        'FieldName' => 'SoftKeywords',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '8',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      9 => 
      array (
        'ContentFieldID' => '12',
        'TableID' => '2',
        'FieldTitle' => '开 发 商',
        'FieldName' => 'Developer',
        'FieldType' => 'varchar',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '9',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      10 => 
      array (
        'ContentFieldID' => '11',
        'TableID' => '2',
        'FieldTitle' => '软件介绍',
        'FieldName' => 'Intro',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'RichEditor',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '10',
        'FieldListDisplay' => '0',
        'IsMainField' => '1',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      11 => 
      array (
        'ContentFieldID' => '19',
        'TableID' => '2',
        'FieldTitle' => '下载地址',
        'FieldName' => 'Download',
        'FieldType' => 'text',
        'FieldSize' => NULL,
        'FieldInput' => 'textaera',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '11',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '1',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      12 => 
      array (
        'ContentFieldID' => '24',
        'TableID' => '2',
        'FieldTitle' => '自定义相关软件 ',
        'FieldName' => 'CustomSoftLinks',
        'FieldType' => 'contentlink',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '12',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
      13 => 
      array (
        'ContentFieldID' => '25',
        'TableID' => '2',
        'FieldTitle' => '自定义相关文章 ',
        'FieldName' => 'CustomLinks',
        'FieldType' => 'contentlink',
        'FieldSize' => '250',
        'FieldInput' => 'text',
        'FieldDefaultValue' => NULL,
        'FieldInputFilter' => NULL,
        'FieldInputPicker' => NULL,
        'FieldInputTpl' => NULL,
        'FieldDescription' => NULL,
        'FieldOrder' => '13',
        'FieldListDisplay' => '0',
        'IsMainField' => '0',
        'IsTitleField' => '0',
        'FieldSearchable' => '0',
        'EnableContribution' => '1',
        'EnableCollection' => '1',
        'EnablePublish' => '1',
      ),
    ),
    'MainField' => 'Intro',
  ),
);
?>