<?php
//CMS cache file, DO NOT modify me!
//Created on June 10, 2010, 15:49

$NodeInfo = array (
  'NodeID' => '8',
  'NodeGUID' => '',
  'TableID' => '1',
  'ParentID' => '1',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '世博讨论区',
  'ContentPSN' => '',
  'ContentURL' => '',
  'ResourcePSN' => '{PSN:1}/res',
  'ResourceURL' => '{PSN-URL:1}/res',
  'PublishMode' => '2',
  'IndexTpl' => '/71zl/list.html',
  'IndexName' => 'index.html',
  'ContentTpl' => '/71zl/content.html',
  'ImageTpl' => '',
  'SubDir' => 'Y-m-d',
  'PublishFileFormat' => '{TimeStamp}d{ContentID}.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '1',
  'IndexPortalURL' => '/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => '/publish/content.php/{IndexID},{Page}.html',
  'Pager' => 'default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => NULL,
  'PermissionManageU' => NULL,
  'PermissionReadG' => NULL,
  'PermissionReadU' => NULL,
  'PermissionWriteG' => NULL,
  'PermissionWriteU' => NULL,
  'PermissionApproveG' => NULL,
  'PermissionApproveU' => NULL,
  'PermissionPublishG' => NULL,
  'PermissionPublishU' => NULL,
  'PermissionInherit' => NULL,
  'CreationUserID' => '1',
  'SubNodeID' => '8',
  'ParentNodeID' => '1%8',
  'Nav' => 'a:2:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:15:"7.1党的生日";}i:1;a:2:{s:6:"NodeID";s:1:"8";s:4:"Name";s:15:"世博讨论区";}}',
  'URL' => '/publish/index.php/8,0.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '7.1党的生日',
      'URL' => '/publish/index.php/1,0.html',
      'NodeName' => '7.1党的生日',
      'NodeURL' => '/publish/index.php/1,0.html',
    ),
    1 => 
    array (
      'NodeID' => '8',
      'Name' => '世博讨论区',
      'URL' => '/publish/index.php/8,0.html',
      'NodeName' => '世博讨论区',
      'NodeURL' => '/publish/index.php/8,0.html',
    ),
  ),
);
?>