<?php
//CMS cache file, DO NOT modify me!
//Created on June 12, 2010, 10:32

$NodeInfo = array (
  'NodeID' => '1',
  'NodeGUID' => 'com.cmsware.demo',
  'TableID' => '1',
  'ParentID' => '0',
  'RootID' => '0',
  'InheritNodeID' => '0',
  'NodeType' => '1',
  'NodeSort' => '0',
  'Name' => '7.1党的生日',
  'ContentPSN' => '{PSN:1}',
  'ContentURL' => '{PSN-URL:1}',
  'ResourcePSN' => '{PSN:1}',
  'ResourceURL' => '{PSN-URL:1}',
  'PublishMode' => '2',
  'IndexTpl' => '/71zl/index.html',
  'IndexName' => 'index.html',
  'ContentTpl' => '/71zl/content.html',
  'ImageTpl' => '/default/image.html',
  'SubDir' => '',
  'PublishFileFormat' => '{ContentID}.html',
  'IsComment' => '0',
  'CommentLength' => NULL,
  'IsPrint' => '0',
  'IsGrade' => '0',
  'IsMail' => '0',
  'Disabled' => '0',
  'AutoPublish' => '1',
  'IndexPortalURL' => 'http://172.27.203.81:8080/subject/djnews/71/publish/index.php/{NodeID},{Page}.html',
  'ContentPortalURL' => 'http://172.27.203.81:8080/subject/djnews/71/publish/content.php/{IndexID},{Page}.html',
  'Pager' => 'default.php',
  'Editor' => 'default.php',
  'WorkFlow' => '0',
  'PermissionManageG' => NULL,
  'PermissionManageU' => NULL,
  'PermissionReadG' => NULL,
  'PermissionReadU' => NULL,
  'PermissionWriteG' => NULL,
  'PermissionWriteU' => NULL,
  'PermissionApproveG' => NULL,
  'PermissionApproveU' => NULL,
  'PermissionPublishG' => NULL,
  'PermissionPublishU' => NULL,
  'PermissionInherit' => NULL,
  'CreationUserID' => NULL,
  'SubNodeID' => '1%2%3%4%5%6%7%8',
  'ParentNodeID' => '1',
  'Nav' => 'a:1:{i:0;a:2:{s:6:"NodeID";s:1:"1";s:4:"Name";s:15:"7.1党的生日";}}',
  'URL' => 'http://172.27.203.81:8080/subject/djnews/71/publish/index.php/1,0.html',
  'Navigation' => 
  array (
    0 => 
    array (
      'NodeID' => '1',
      'Name' => '7.1党的生日',
      'URL' => 'http://172.27.203.81:8080/subject/djnews/71/publish/index.php/1,0.html',
      'NodeName' => '7.1党的生日',
      'NodeURL' => 'http://172.27.203.81:8080/subject/djnews/71/publish/index.php/1,0.html',
    ),
  ),
);
?>